### PR TITLE
Created CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by tvermaashutosh**
Issue #5 

Created CONTRIBUTING.md file in your repository.
@Pinaka-Pani-18 Please merge my PR and add the `hacktoberfest-accepted` tag in it.

### CODE REVIEW

**Review by Pinaka-Pani-18 — CHANGES_REQUESTED** [review]
Could you please add images with examples of Git commands?

For example, for the Git command : git commit -m "Relevant message",
the image should display something like: git commit -m "Fixed the bugs in the navbar"

**Comment by tvermaashutosh** [comment]
Sure @Pinaka-Pani-18 . I'll do it just now!

**Comment by Pinaka-Pani-18** [comment]
> Sure @Pinaka-Pani-18 . I'll do it just now!

Okay, please add example images of Git commands below the respective Git command.

**Comment by tvermaashutosh** [comment]
@Pinaka-Pani-18 I have successfully added the images with examples of Git commands below the respective Git command.
Please merge my PR and add the `hacktoberfest-accepted` tag in it.

**Review by Pinaka-Pani-18 — APPROVED** [review]

**Pull request merged**
